//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReclameTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Cidade()
        {
            this.tb_Consumidor = new HashSet<tb_Consumidor>();
        }
    
        public int Id_Cidade { get; set; }
        public string nomeCidade { get; set; }
        public string cep { get; set; }
        public Nullable<int> fk_Estado { get; set; }
    
        public virtual tb_Estado tb_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Consumidor> tb_Consumidor { get; set; }
    }
}
