//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReclameTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Comentario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Comentario()
        {
            this.tb_Comentario1 = new HashSet<tb_Comentario>();
            this.tb_Reclamacao = new HashSet<tb_Reclamacao>();
        }
    
        public int Id_comentario { get; set; }
        public string comentario { get; set; }
        public Nullable<int> fk_comentario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Comentario> tb_Comentario1 { get; set; }
        public virtual tb_Comentario tb_Comentario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Reclamacao> tb_Reclamacao { get; set; }
    }
}
