//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReclameTech.Models
{
    using System;

    public partial class tb_Reclamacao
    {
        public int Id_reclamacao { get; set; }
        public System.DateTime data { get; set; }
        public string produtoEmpresa { get; set; }
        public string respostaEmpresa { get; set; }
        public string tituloReclamacao { get; set; }
        public string prestadorServico { get; set; }
        public Nullable<int> fk_consumidor { get; set; }
        public Nullable<int> fk_status { get; set; }
        public Nullable<int> fk_empresa { get; set; }
        public Nullable<int> fk_comentario { get; set; }
    
        public virtual tb_Comentario tb_Comentario { get; set; }
        public virtual tb_Consumidor tb_Consumidor { get; set; }
        public virtual tb_Empresa tb_Empresa { get; set; }
        public virtual tb_Status tb_Status { get; set; }
    }
}
